include("src/modules/1_hello-world_test.jl")
include("src/modules/2_leap_test.jl")
include("src/modules/3_nucleotide-count_test.jl")
include("src/modules/4_pangram_test.jl")
include("src/modules/5_rotational-cipher_test.jl")
include("src/modules/6_differences-of-squares_test.jl")
include("src/modules/7_raindrops_test.jl")
